config/routes.rb
Rails.application.routes.draw do
  
  root :to => "campaigns#index" 
  
  resources :campaigns
  resources :customers
  resources :friend_offers
  resources :advocate_offers
  
  resources :campaign_builder
  

end

app/models/advocate_offer.rb
class AdvocateOffer < ActiveRecord::Base

  # has_one :campaign

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  
  #has_many :customer_campaigns
  belongs_to :advocate_offer 
  belongs_to :friend_offer 
  has_many :customer_campaigns 
  has_many :customers, :through => :customer_campaigns
  
  
  #  belongs_to :advocate_offer 
  # belongs_to :friend_offer 
  
  # attr_writer :current_step
  
  # def steps
    # %w[basic_info advocate_offer friend_offer]
  # end
  
  # def current_step
    # @current_step || steps.first
  # end
#   
  # def next_step
    # self.current_step = steps[steps.index(current_step)+1]
  # end
#   
  # def previous_step
    # self.current_step = steps[steps.index(current_step)-1]
  # end
#   
  # def first_step?
    # current_step == steps.first
  # end
#   
  # def last_step?
    # current_step == steps.last
  # end
  
end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :codes
  has_many :customer_campaigns 
  has_many :campaigns, :through => :customer_campaigns
end

app/models/customer_campaign.rb
class CustomerCampaign < ActiveRecord::Base
  belongs_to :customer
  belongs_to :campaign
end

app/models/friend_offer.rb
class FriendOffer < ActiveRecord::Base
  
  # has_one :campaign
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaign_builder_controller.rb
class CampaignBuilderController < ApplicationController
  
  include Wicked::Wizard
  
  steps :advocate_offer, :friend_offer
  
  def show
    @campaign = Campaign.find(params[:campaign_id])
    render_wizard
    
  end
  
  
  def update
    puts "=================================="
    puts params
    puts "=================================="
    @campaign = Campaign.find(params[:id])
    @campaign.update_attributes(campaign_params)
    render_wizard @campaign
    
    
    # session[:campaign_params].deep_merge!(campaign_params) if campaign_params
    # @campaign = Campaign.new(session[:campaign_params])
    # # @advocate_offer = AdvocateOffer.new(advocate_offer_params)
    # # @friend_offer = FriendOffer.new(friend_offer_params)
#     
    # @campaign.current_step = session[:campaign_step]
    # if params[:previous_button]
      # @campaign.previous_step
    # elsif @campaign.last_step?
      # @campaign.save
    # else
      # @campaign.next_step
    # end
    # session[:campaign_step] = @campaign.current_step
    # if @campaign.new_record?
      # render "new"
    # else
      # flash[:notice] = "Campaign created"
      # redirect_to @campaign
    # end
  end
    
  private

    def campaign_params
      # same as using "params[:campaign]", except that it:
      # - raises an error if :campaign is not present
      # - allows listed attributes to be mass-assigned
      params.require(:campaign).permit( :campaign_name, :campaign_description, :campaign_start_date, :campaign_end_date, :advocate_offer_type, :advocate_min_purchse, :advocate_review_period, :referral_code_limit, :friend_offer_type, :friend_min_purchse ) 
                                       
    end  
    
    # def advocate_offer_params
      # # same as using "params[:campaign]", except that it:
      # # - raises an error if :campaign is not present
      # # - allows listed attributes to be mass-assigned
      # params.require(:advocate_offer).permit( :advocate_offer_type, :advocate_start_date, :advocate_end_date, :advocate_min_purchse, :advocate_review_period, :referral_code_limit) 
      #                                        
    # end 
    
    # def friend_offer_params
      # # same as using "params[:campaign]", except that it:
      # # - raises an error if :campaign is not present
      # # - allows listed attributes to be mass-assigned
      # params.require(:friend_offer).permit(:friend_offer_type, :friend_start_date, :friend_end_date, :friend_min_purchse) 
      #                                        
    # end   
    
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  
  layout 'client'
  
  def index
    @campaigns = Campaign.order("campaign_start_date DESC")
  end
  
  def show
    @campaign = Campaign.find(params[:id])
  end
  
  def new
    # session[:campaign_params] ||= {}
    @campaign = Campaign.new
  end
  
  def create
    @campaign = Campaign.new(campaign_params)
    
    if @campaign.save
      # redirect_to campaign_builder_path(:id => "advocate_offer", :campaign_id => @campaign.id)
      flash[:notice] = "Campaign created successfully."
      redirect_to(:action => 'index')
    else
      render 'new'
    end
  end
    
  private

    def campaign_params
      # same as using "params[:campaign]", except that it:
      # - raises an error if :campaign is not present
      # - allows listed attributes to be mass-assigned
      params.require(:campaign).permit( :campaign_name, :campaign_description, :campaign_start_date, :campaign_end_date, :advocate_offer_type, :advocate_min_purchase, :advocate_review_period, :referral_code_limit, :friend_offer_type, :friend_min_purchase) 
                                       
    end    
     
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
   
  layout "client"
  
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def new
  end
  
  def create
    @customer = Customer.new(customer_params)
    @temp = Customer.find_by_referral_code(@customer.referral_code)
    Rails.logger.info("$$$$444444444444444444444444444$$$$$$$$$******************2$$$$$$$$$$$$$$$$$#{@temp.inspect}")
    if @temp.nil?
      @customer.referral_code = @customer.first_name.split(//).first(3).join + @customer.last_name.split(//).first(3).join
      if @customer.save
        @caid = Campaign.find_by_campaign_status(1) 
        Rails.logger.info("**************")
        Rails.logger.info(@customer.inspect)
        Rails.logger.info("**************")
        @custcamp = CustomerCampaign.create(:customer => @customer, :campaign => @caid, :no_of_referrals => 0)
        redirect_to(:action => 'index')
      else
        render('new')
      end
    else
         @customer.referred_by = @temp.first_name + @temp.last_name
         @customer.referral_code = @customer.first_name.split(//).first(3).join + @customer.last_name.split(//).first(3).join
         if @customer.save
              @caid = Campaign.find_by_campaign_status(1) 
              # Rails.logger.info("$$$$$$$$$$$$$******************2$$$$$$$$$$$$$$$$$#{@caid.inspect}")
              @custcamp = CustomerCampaign.create(:customer => @customer, :campaign => @caid, :no_of_referrals => 0)
              c = @temp.no_of_referrals + 1
              @temp.update_attributes(:no_of_referrals => c)
              @cctemp = CustomerCampaign.where(:customer_id => @temp.id, :campaign_id => @caid.id).first
              Rails.logger.info("$$$$$$$$$$$$$$$$$$$$$$$$$$#{@cctemp.inspect}")
              k = @cctemp.no_of_referrals + 1
              @cctemp.update_attributes(:no_of_referrals => k)
              
                if @temp.no_of_referrals.even?
                   # /*generate new row for ccustomer.id in code table */
                    @code = Code.new(:redemption_code => "aaaa"  ,:redeemed_on => nil)
                    if @code.save
                      @temp.codes << @code  
                    end
                    
                    
                else
                end
         redirect_to(:action => 'index')
         else
          render('new')
         end
    end
  end
  
  def edit
  end
  
  def new_code
    code.new()
  end
  
  
  
  private
  def customer_params
     params.require(:customer).permit(:first_name, :last_name, :email, :mobile, :referral_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_builder_helper.rb
module CampaignBuilderHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaign_builder/_email.html.erb
<h2>Advocate Offer<h2>
<table class="campaign form fields">
      <tr>
        <th>Type</th>
        <td><%= f.text_field(:advocate_offer_type) %></td>
      </tr>
      <tr>
        <th>Start Date</th>
        <td><%= f.text_area(:advocate_start_date) %></td>
      </tr>
      <tr>
        <th>End Date</th>
        <td><%= f.text_field(:advocate_end_date) %></td>
      </tr>
      <tr>
        <th>Minimum Purchase</th>
        <td><%= f.text_field(:advocate_min_purchase) %></td>
      </tr>
      <tr>
        <th>Review Period</th>
        <td><%= f.text_field(:advocate_review_period) %></td>
      </tr>
      <tr>
        <th>Referral Code Limit</th>
        <td><%= f.text_field(:referral_code_limit) %></td>
      </tr>
    </table>

app/views/campaign_builder/advocate_offer.html.erb
<h2>Advocate Offer<h2>

<%= form_for(:campaign, :url => wizard_path(:id=>@campaign.id), :method => :put) do |f|  %>
  
    <table class="campaign form fields">
      <tr>
        <th>Offer Type</th>
        <td><%= f.text_field(:advocate_offer_type) %></td>
      </tr>
      <tr>
        <th>Min purchase</th>
        <td><%= f.text_field(:advocate_min_purchase) %></td>
      </tr>
      <tr>
        <th>Review Period</th>
        <td><%= f.text_field(:advocate_review_period) %></td>
      </tr>
      <tr>
        <th>Referral Code Limit</th>
        <td><%= f.text_field(:referral_code_limit) %></td>
      </tr>
    </table>

	

  <%= submit_tag "Next"%>
  
<% end %>

app/views/campaign_builder/friend_offer.html.erb
<h2>Friend Offer<h2>
		
<%= form_for(:campaign, :url => wizard_path, :method => :put) do |f|  %>

	<table class="campaign form fields">
      <tr>
        <th>Type</th>
        <td><%= f.text_field(:friend_offer_type) %></td>
      </tr>
      <tr>
        <th>Minimum Purchase</th>
        <td><%= f.text_field(:friend_min_purchase) %></td>
      </tr>   
   </table>

<%= submit_tag "Next"%>
  
<% end %>

app/views/campaigns/_form.html.erb
<h2>Basic Info</h2>

	
	<div class="form-group">
        <%= f.label(:campaign_name) %>
        <%= f.text_field(:campaign_name, :class => "form-control", :placeholder => "Enter Campaign Name") %>
      </div>
      
      <div class="form-group">
        <%= f.label(:campaign_description) %>
        <%= f.text_area(:campaign_description, :class => "form-control", :placeholder => "Enter Description") %>
      </div>
      
      <div class="form-group">
        <%= f.label(:start_date) %>
        <%= f.date_select(:campaign_start_date, :order => [:day, :month, :year], :class => "form-control") %> --
        <%= f.time_select(:campaign_start_date, :include_seconds => true, :ignore_date => true, :ampm => true) %> 
       </div>     
      
      <div class="form-group">
        <%= f.label(:end_date) %>
        <%= f.date_select(:campaign_end_date, :order => [:day, :month, :year]) %> -- 
        <%= f.time_select(:campaign_end_date, :include_seconds => true, :ignore_date => true, :ampm => true) %>
      </div>
      
 <h2>Advocate Offer</h2>

      <div class="form-group">
        <%= f.label(:advocate_offer_type) %>
        <%= f.text_field(:advocate_offer_type, :class => "form-control", :placeholder => "Enter Advocate Offer") %>
      </div>
      
      <div class="form-group">
        <%= f.label(:advocate_min_purchase) %>
        <%= f.text_field(:advocate_min_purchase, :class => "form-control", :placeholder => "Enter Advocate Min Purchase") %>
      </div>
      
      <div class="form-group">
        <%= f.label(:advocate_review_period) %>
        <%= f.text_field(:advocate_review_period, :class => "form-control", :placeholder => "Enter Advocate Review Period") %>
      </div>
     
     <div class="form-group">
        <%= f.label(:referral_code_limit) %>
        <%= f.text_field(:referral_code_limit, :class => "form-control", :placeholder => "Enter Referral Code Limit") %>
      </div>


<h2>Friend Offer</h2>

      <div class="form-group">
        <%= f.label(:friend_offer_type) %>
        <%= f.text_field(:friend_offer_type, :class => "form-control", :placeholder => "Enter Friend Offer Type") %>
       </div>
      
      <div class="form-group">
        <%= f.label(:friend_min_purchase) %>
        <%= f.text_field(:friend_min_purchase, :class => "form-control", :placeholder => "Enter Friend Min Purchase") %>
         </div>

app/views/campaigns/index.html.erb
<% @page_title = "Campaigns" %>

<div class="campaigns-index">
  <h1 style="text-align: center">CAMPAIGNS</h1>

  <%= link_to(" Add Campaign", {:action => 'new'}, :class => 'glyphicon glyphicon-plus btn btn-info')%> 
 
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th>Campaign Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Advocate Offer</th>
      <th>Advocate Min Purchase</th>
      <th>Friend Offer</th>
      <th>Friend Min Purchase</th>
      <th>Campaign Status</th>
      <th>Actions</th>
    </tr>
    <% @campaigns.each do |c| %>
    <tr>
      <td><%= c.campaign_name %></td>
      <td><%= c.campaign_start_date.strftime("%d-%b-%Y, %I:%M:%S %p") %></td>
      <td><%= c.campaign_end_date.strftime("%d-%b-%Y, %I:%M:%S %p") %></td>
      <td><%= c.advocate_offer_type %></td>
      <td><%= c.advocate_min_purchase %></td>
      <td><%= c.friend_offer_type %></td>
      <td><%= c.friend_min_purchase %></td>
      <td>
      	<% if c.campaign_status == true %>
      	<p>Active</p>
      	<% else %>
      	<p>Inactive</p>
      	<% end %>
      </td>
      <td>
        <%= link_to("Show", {:action => 'show', :id => c.id}, :class => 'action-show') %>
        
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/campaigns/new.html.erb
<% @page_title = "Add Campaign" %>

<div class="campaigns new">
	<h1 style="text-align: center">ADD CAMPAIGN</h1>
	<%= link_to("<< Back to List",{:action => 'index'},:class =>'btn btn-info')%>


<div class="container">
<div class="jumbotron">
	
	
  <%= form_for(:campaign, :url => {:action => 'create'}) do |f| %>

    <%= render({:partial => "form", :locals => {:f => f}}) %>
    
    <%= submit_tag "Create", :class => "btn btn-default"%>

  <% end %>
  
  
  
  </div>
  </div>
  
</div>

app/views/campaigns/show.html.erb
<% @page_title = "Show Campaign" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back link') %>

<div class="campaigns show">
  <h2>Show Campaign</h2>

  <table class="campaign detail view">
    <tr>
      <th>Campaign No.</th>
      <td><%= @campaign.id %></td>
    </tr>
    <tr>
      <th>Campaign Name</th>
      <td><%= @campaign.campaign_name %></td>
    </tr>
    <tr>
      <th>Campaign Description</th>
      <td><%= @campaign.campaign_description %></td>
    </tr>
    <tr>
      <th>Start Date</th>
      <td><%= @campaign.campaign_start_date %></td>
    </tr>
    <tr>
      <th>End Date</th>
      <td><%= @campaign.campaign_end_date %></td>
    </tr>
    <tr>
      <th>Advocate Offer</th>
      <td><%= @campaign.advocate_offer_type %></td>
    </tr>
    <tr>
      <th>Advocate Min Purchase</th>
      <td><%= @campaign.advocate_min_purchase %></td>
    </tr>
    <tr>
      <th>Friend Offer</th>
      <td><%= @campaign.friend_offer_type %></td>
    </tr>
    <tr>
      <th>Friend Min Purchase</th>
      <td><%= @campaign.friend_min_purchase %></td>
    </tr>
    <tr>
      <th>Review Period</th>
      <td><%= @campaign.advocate_review_period %></td>
    </tr>
    <tr>
      <th>Referral Code Limit</th>
      <td><%= @campaign.referral_code_limit %></td>
    </tr>
    <tr>
      <th>Created at</th>
      <td><%= @campaign.created_at %></td>
    </tr>
  </table>

</div>

app/views/customers/index.html.erb
<div class="customers index"></div>
<h1 style="text-align: center">CUSTOMERS</h1>
<%= link_to("Add New Customer",{:action => 'new'},:class =>'btn btn-info')%>

<table class="table table-hover">
	<thead>
		<tr class="header">
			<th>S.No.</th>          	
			<th>Customer</th>                
			<th>Email</th>                   
			<th>Mobile</th>
			<th>Referred By</th>                  
			<th>Actions</th>                 
		</tr>
	</thead>
	<tbody>
		<% @customers.each do |customer| %>
		<a href="customer_path" class="table-row">	
			<td class="center"><%= customer.id%></td>
			<td class="center"><%= customer.first_name %>  <%= customer.last_name %></td>
			<td class="center"><%= customer.email %></td>
			<td class="center"><%= customer.mobile%></td>
			<td class="center"><%= customer.referred_by%></td>
			<td class="center">
				<%= link_to("show",{:action => 'show',:id => customer.id},:class=>'action show')%>
				<%= link_to("edit",{:action => 'edit',:id => customer.id},:class=>'action edit')%>
			</a>
			
		</tr>
		<% end %>
	</tbody>
</table>

app/views/customers/new.html.erb
<div class="customers new">
	<h1 style="text-align: center">ADD CUSTOMER</h1>
	<%= link_to("<< Back to List",{:action => 'index'},:class =>'btn btn-info')%>
<div class="container">
<div class="jumbotron">
	<div class="form-group">
	<%= form_for(:customer, :url =>{:action => 'create'}) do |f| %>
	
		<table>
			<tr>
				<th>First Name</th>
				<td><%= f.text_field(:first_name)%></td>
			</tr>
			<tr>
				<th>Last Name</th>
				<td><%= f.text_field(:last_name)%></td>
			</tr>
			<tr>
				<th>Email ID</th>
				<td><%= f.text_field(:email)%></td>
			</tr>
			<tr>
				<th>Contact Number</th>
				<td><%= f.text_field(:mobile)%></td>
			</tr>
			<tr>
				<th>Refferal code</th>
				<td><%= f.text_field(:referral_code)%></td>
			</tr>
			
					
		</table>
		<%= submit_tag("ADD")%>
 </div>
	<% end %>
</div>
</div>	
	
</div>
	

app/views/customers/show.html.erb
	<h1 style="text-align: center" > <%= @customer.first_name.capitalize %> <%= @customer.last_name.capitalize %> </h1>
	<div style="display: inline">	
	<h3 style="margin-left: 8%">Serial Number: <span style="font-size: 85%; margin-left: 4%"><%= @customer.id%></span></h3>
	</div>	
	<h3 style="margin-left: 8%">Email Id: <span style="font-size: 85%; margin-left: 9%"><%= @customer.email %></span></h3>          
	<h3 style="margin-left: 8%">Mobile Number: <span style="font-size: 85%; margin-left: 3%"><%= @customer.mobile %></span></h3>     
	<h3 style="margin-left: 8%">Reffered By: <span style="font-size: 85%; margin-left: 5%"><%= @customer.referred_by %></span></h3>       
	<h3 style="margin-left: 8%">Referral Code: <span style="font-size: 85%; margin-left: 4%"><%= @customer.referral_code %></span></h3>
	<h3 style="margin-left: 8%">Total No of Referrals: <span style="font-size: 85%; margin-left: 4%"><%= @customer.no_of_referrals %></span></h3> 
	<h3 style="margin-left: 8%">Current No of Referrals: <span style="font-size: 85%; margin-left: 4%"><%= @customer.no_of_referrals %></span></h3>    

	
<h2 style="text-align: center;margin-top: 10%;">Redemption History</h2>

<div class="container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>S.No</th>          	
				<th>REDEMPTION CODE</th>
				<th>DATE OF REDEMPTION</th>                                
			</tr>
		</thead>
		<tbody>
			<% @customer.codes.each do |code| %>
			<tr>	
				<td><%= code.id%></td>
				<td><%= code.redemption_code %></td>
				<td>
					<% if code.redeemed_on.nil? %>
					   UN-USED
					<% else %>
					   <%= code.redeemed_on %>
					<% end %>
				</td>		
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Referral Manager</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	   <meta content="width=device-width, initial-scale=1" name="viewport"/>
	   <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"></link>
	   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	   <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	</head>
	<body>
	
	<%= yield %>
	
	</body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Referral Manager | <%= @page_title %></title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	   <meta charset="utf-8">
	   <meta content="width=device-width, initial-scale=1" name="viewport"/>
	   <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"></link>
	   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	   <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body>
  	
	    <nav class="navbar navbar-inverse">
		    <div class="navbar-header">
		    	<a class="navbar-brand" href="#">Referral Manager</a>
		    </div>
		    <div>
		    	<ul class="nav navbar-nav">
		    		<li class="dropdown">
		   				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Monitor<span class="caret"></span></a>
				      		<ul class="dropdown-menu">
				        		<li><a href="#"> Analytics Overview </a></li>
				        		<li><a href="#"> Recent Activity</a></li>                        
				      		</ul>
		    		</li>
		    		<li class="dropdown">
		    			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Configure<span class="caret"></span></a>
				      		<ul class="dropdown-menu">
				        		<li><%= link_to "Campaigns", campaigns_path %></li>
				        		<li><a href="#">  </a></li>                        
				      		</ul>
		    		</li>
		    		<li class="dropdown">
		    			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Manage<span class="caret"></span></a>
				      		<ul class="dropdown-menu">
				        		<li><%= link_to "Customers", customers_path %>  </li>
				        		<li><a href="#">  </a></li>                        
				      		</ul>
		    		</li>
		    	</ul>
		    </div>
	    </nav>
	
			
	   <% if !flash[:notice].blank? %>
	   		<div class="alert alert-success fade-in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			    <%= flash[:notice] %>
	   	    </div>
	   <% end %>
			      
		<div class="container-fluid">
			<%= yield %>
		</div>
		
		<nav class="navbar navbar-inverse">
			<footer>
				<p class="copyright">&copy; Birdvision Consulting Pvt. Ltd.</p>
			</footer>
		</nav>	
		
  </body>
</html>